name: dp_cf_turnstile_bypass

on:
  schedule:
    - cron: "21 0,10 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'
           cache: 'pip'

      - name: Install requirements
        run: |
          pip install -r requirements_cf.txt

      
      - name: test
        run: python3 dp_bypass_cf.py
