name: tag release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '输入tag版本号'
        required: true

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./stealth.min.js
        #asset_name: mything_name
        tag: ${{ github.event.inputs.tag }}
        overwrite: true
        body: "This is my release text"
