name: 'test_ac'

on:
  #schedule:
    #- cron: "3 18 */15 * *"
  # 点击star时触发运行
  #watch:
    #types: started
  # 手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
 #     - name: test
 #       env:
 #         workflow_name: ${{ github.workflow_ref }}
 #       run: |
 #         echo ${{ github.workflow_ref }}
 #         ls -a
 #         echo ${workflow_name%%@*}
 #         mkdir dists && cp -r ./.github ./dists
 #         ls -a . ./dists/.github
 #         workflow_name=$(echo "${workflow_name}" | sed 's/^[^/]*\/[^/]*\///;s/@.*$//')
 #         cat ${workflow_name}


      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y g++
      
      - name: run bash
        env:
          workflow_name: ${{ github.workflow_ref }}
        run: |
          echo ${{ github.run_id }}
          echo ${{ github.workflow_ref }}
          pwd
          cd .github && ls -a
          echo "------"
          cd .. && ls -a
          echo "gcc"
          gcc --version
          echo "chrome"
          command -v google-chrome-stable
          google-chrome-stable --version
          echo "chromedriver"
          command -v chromedriver
          chromedriver --version
          #google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222
          #curl -sL http://127.0.0.1:9222/json/version
          # echo ${{ secrets }}
          export
